service: clean-clear-confident-server

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2

functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'